// data.jsx — sample data + i18n strings

const CATALOG = [
  {
    code: 'MP-100RM-GARE5',
    barcode: '9556789001234',
    name: 'Asia Pump MP-100RM-GARE5',
    brand: 'Asia Pump',
    category: 'Pumps · Magnetic Drive',
    uom: 'ea',
    price: 1280.00,
    location: 'Aisle 2 · Bin 04',
    stock: 6,
  },
  {
    code: 'BG-H5K-CPU',
    barcode: '5060162270123',
    name: 'B&G H5000 CPU Hercules',
    brand: 'B&G',
    category: 'Instruments',
    uom: 'ea',
    price: 2450.00,
    location: 'Aisle 3 · Bin 12',
    stock: 2,
  },
  {
    code: 'VIC-SC-75-15',
    barcode: '8719076035512',
    name: 'Victron SmartSolar MPPT 75/15',
    brand: 'Victron',
    category: 'Solar · Charge Controllers',
    uom: 'ea',
    price: 165.00,
    location: 'Aisle 5 · Bin 08',
    stock: 11,
  },
  {
    code: 'SIKA-291-BLK',
    barcode: '7612895012345',
    name: 'Sikaflex-291 Black 300ml',
    brand: 'Sika',
    category: 'Sealants · Adhesives',
    uom: 'ea',
    price: 28.50,
    location: 'Aisle 1 · Bin 02',
    stock: 24,
  },
  {
    code: 'CBL-TNN-6MM',
    barcode: '4901234567890',
    name: 'Tinned Marine Cable 6mm²',
    brand: 'Oceanflex',
    category: 'Electrical · Cable',
    uom: 'm',
    price: 3.20,
    location: 'Aisle 4 · Reel 01',
    stock: 180,
  },
];

const I18N = {
  en: {
    sop_title: 'Parts Logger — Technician SOP',
    sop_sub: 'Scan parts as you take them off the shelf. Your Scheduler exports the sheet into Excel for invoicing.',
    job: 'Active Job',
    tech: 'Technician',
    boat: 'Customer / Boat',
    date: 'Date',
    items_logged: 'Items logged',
    scan_product: 'Scan product barcode',
    scan_hint: 'Align the barcode inside the frame',
    manual_search: 'Type code / name instead',
    no_barcode: 'No barcode? Log as unknown',
    scan_success: 'Product matched',
    confirm_add: 'Add to job',
    quantity: 'Quantity',
    save_item: 'Save item',
    cancel: 'Cancel',
    usage_log: 'Items used on this job',
    add_another: 'Scan another item',
    submit_job: 'Submit to sheet',
    sync_done: 'Synced to Project Usage sheet',
    sync_sub: 'Scheduler can export as Excel for invoicing.',
    done: 'Done',
    unknown_title: 'Log unknown item',
    unknown_sub: 'No barcode or SKU — describe and photograph so shop team can add it later.',
    description: 'Description',
    take_photo: 'Tap to add photo',
    flag_review: 'Flag for Scheduler review',
    search_placeholder: 'Search code or name',
    results: 'Matches',
    offline: 'Offline — queued',
    online: 'Online — synced',
    unit: 'unit',
    units: 'units',
    metres: 'metres',
  },
  ms: {
    sop_title: 'Daftar Alat Ganti — SOP Juruteknik',
    sop_sub: 'Imbas setiap item bila diambil dari rak. Penjadual akan eksport ke Excel untuk invois.',
    job: 'Kerja Aktif',
    tech: 'Juruteknik',
    boat: 'Pelanggan / Bot',
    date: 'Tarikh',
    items_logged: 'Item didaftar',
    scan_product: 'Imbas barcode produk',
    scan_hint: 'Letak barcode dalam bingkai',
    manual_search: 'Taip kod / nama produk',
    no_barcode: 'Tiada barcode? Daftar sebagai tidak dikenali',
    scan_success: 'Produk dikenali',
    confirm_add: 'Tambah ke kerja',
    quantity: 'Kuantiti',
    save_item: 'Simpan item',
    cancel: 'Batal',
    usage_log: 'Item digunakan untuk kerja ini',
    add_another: 'Imbas item seterusnya',
    submit_job: 'Hantar ke sheet',
    sync_done: 'Tersimpan dalam Project Usage sheet',
    sync_sub: 'Penjadual boleh eksport ke Excel untuk invois.',
    done: 'Selesai',
    unknown_title: 'Daftar item tidak dikenali',
    unknown_sub: 'Tiada barcode atau rekod — huraikan dan ambil foto.',
    description: 'Huraian',
    take_photo: 'Ketik untuk ambil foto',
    flag_review: 'Tanda untuk semakan Penjadual',
    search_placeholder: 'Cari kod atau nama',
    results: 'Padanan',
    offline: 'Luar talian — beratur',
    online: 'Dalam talian — selaras',
    unit: 'unit',
    units: 'unit',
    metres: 'meter',
  },
};

const SOP_STEPS = [
  { id: 'home', title: 'Open active job', desc: 'Tech opens the app. Today\'s job is already pinned: Hafifi · SV Sula. Sync chip top-right shows online / offline state.' },
  { id: 'scan', title: 'Tap Scan product', desc: 'Camera opens to the viewfinder. No menus. One-handed with gloves on.' },
  { id: 'scan_match', title: 'Barcode matched', desc: 'App reads the code, looks it up in the Products master, shows item for confirmation.' },
  { id: 'qty', title: 'Enter quantity', desc: 'Big +/– stepper. Default is 1. Tech taps Save.' },
  { id: 'log', title: 'Item added to log', desc: 'Usage list grows. Tech can keep scanning, edit a row, or submit.' },
  { id: 'search', title: 'Fallback — manual search', desc: 'If barcode is damaged, tech types the SKU or name.' },
  { id: 'unknown', title: 'Fallback — unknown item', desc: 'For cable offcuts, generic screws, labelless tubes. Flagged for Scheduler.' },
  { id: 'submit', title: 'Submit to sheet', desc: 'Rows flush to the Project Usage Excel. Scheduler downloads for billing.' },
];

window.CATALOG = CATALOG;
window.I18N = I18N;
window.SOP_STEPS = SOP_STEPS;
